config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Root path
  root "pages#home"

  # Nested routes for projects and tasks
  resources :projects do
    resources :tasks, only: [:new, :create, :edit, :update, :destroy, :show] do
      # Custom routes for starting and stopping work on a task
      member do
        patch :start_work
        patch :stop_work
      end
    end
  end
end

#note pour sid
#j'ai rajouté ces elements mais je dois revenir dessus pour comprendre (sur la partie membe do )

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  enum status: { todo: 0, in_progess: 1, done: 2 }
  validates :name, presence: true

    # def session_duration
    #   if current_session_start.present?
    #     Time.current - current_session_start
    #   else
    #     0
    #   end
    # end

    # # Method to stop the current session and add the time to the total_time_spent
    # def stop_session
    #   if current_session_start.present?
    #     session_time = Time.current - current_session_start
    #     self.total_time_spent ||= 0
    #     update(
    #       total_time_spent: total_time_spent + session_time.to_i, # Cumul du temps total en secondes
    #       current_session_start: nil # Réinitialise la session en cours
    #     )
    #   end
    # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
  has_many :tasks, through: :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  
  def home
    @tasks = Task.all
    @projects = Project.all
    @project = Project.find_by(id: params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  end

  def show
    @project = Project.find(params[:id])
    @status = params[:status]
    if @status
    @tasks = @project.tasks.where(status: @status)
    else
      @tasks = @project.tasks
    end

    if params[:focused_task]
      @focused_task = @project.tasks.find_by(id: params[:focused_task])
      @dontanimate = params[:dontanimate]
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = Task.all
  end

  def show
    @project
    @task
  end

  def new
    @project = Project.find(params[:project_id])  # Récupère le projet associé
    @task = @project.tasks.build # Initialise une nouvelle tâche pour le projet
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(task_params)
    @task.user_id = current_user.id
      if @task.save
        redirect_to @project, notice: "Tâche créée avec succès"
      else
        render :new
      end
  end

  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])




    if @task.update(task_params)
      @focused_task = @task
      respond_to do |format|
        format.html { redirect_to project_path(@project, focused_task:@task.id, dontanimate:true), notice: "Tâche mise à jour avec succès." }
        format.js   # Pour gérer la réponse via AJAX
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.js   # Pour afficher les erreurs via AJAX
      end
    end
  end

  # def start_work
  #   @task = Task.find(params[:id])
  #   if @task.current_session_start.nil?
  #     @task.update(current_session_start: Time.current)
  #   end
  #   redirect_to project_path(@task.project, focused_task: @task.id)
  # end

  # def stop_work
  #   @task = Task.find(params[:id])
  #   @task.stop_session
  #   redirect_to project_path(@task.project, focused_task: @task.id)
  # end



  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :status, :time_task, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Focus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <script src="https://kit.fontawesome.com/1c4ed37e9c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poly:ital@0;1&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="w-screen flex">
   <%= render "pages/navbar" %>
    <main class="flex-grow">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
        <% if user_signed_in? %>
          <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "link-button" %>
        <% end %>
        <div class="p-3"><%= yield %></div>
    </main>
    </div>
  </body>
</html>

app/views/pages/_navbar.html.erb
<div>
  <div class="sidebar">
    <div class="head">
      <div class="user_img">
        <div class="img">
          <img src="https://media.licdn.com/dms/image/v2/C5603AQEhTPs9WZbdaA/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1602105364449?e=1730937600&v=beta&t=_wvFUYe09u31fqhKq_7lhhG3yfqOoY3laW7GwGLKYEA" alt="Profile Image">
        </div>
        <div class="user-details">
          <p class="name">Valentin DUCRETTET</p>
          <p class="title">CTO Facebook</p>
        </div>
      </div>
    </div>


    <div class="nav">
      <div class="menu">
        <div class="navigation">
          <i class="fa-solid fa-house icon"></i>
          <p>Accueil</p>
        </div>

        <div class="navigation">
          <i class="fa-solid fa-address-book icon"></i>
          <p>Rapport</p>
        </div>
        <div class="navigation">
          <i class="fa-solid fa-tag icon"></i>
          <p>Tag</p>
        </div>
        <div class="navigation">
          <i class="fa-solid fa-gear icon"></i>
          <p>Paramètres</p>
        </div>
        <div class="navigation">
          <i class="fa-solid fa-right-from-bracket icon"></i>
          <p><%= link_to "Me déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class:"grey" %></p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<h2 class="title-home">Mes projets en cours</h2>

<div class="projects flex-wrap">
  <% @projects.each do |project| %>
    <%= link_to project_path(project), class: "relative flex flex-col items-center bg-white border border-[#94F956] rounded-lg shadow md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-[#94F956] dark:bg-gray-800 dark:hover:bg-gray-700" do %>
      <!-- Étiquette "Tâche" en haut à gauche -->
      <div class="absolute top-0 left-0 bg-[#94F956] text-white text-xs font-bold px-2 py-1 rounded-tr-lg rounded-bl-lg">
        Projet
      </div>
      <img class="object-cover w-full rounded-t-lg h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-lg" src="https://eeat-haccp.io/wp-content/uploads/2023/12/application_haccp_imprimante_enregistreur_frigo.webp" alt="">
      <div class="flex flex-col justify-between p-4 leading-normal">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= project.name %></h5>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= project.description %></p>
      </div>
    <% end %>
  <% end %>
</div>

</div>

app/views/projects/show.html.erb
<div class="project-title pb-6 flex items-center bg-black">
  <h1 class="title-project pr-5 p-2"><%= @project.name %></h1>
  <div class="mt-2">
  <%= link_to "Créer une nouvelle tâche", new_project_task_path(@project), class: "text-black text-[16px] bg-[#94F956] hover:bg-[#94F956] focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-8 py-2 me-2  focus:outline-none dark:focus:ring-[#94f956]pl-4 " %>
</div>

</div>




<div class="mt-9">
<%= link_to "Tous", project_path(@project)%>
<%= link_to  "A faire", project_path(@project, status: "todo"), class: @status=="todo"? "bg-blue-100 text-white-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-yellow-900 dark:text-yellow-300" :""%>
<%= link_to  "En progression", project_path(@project, status: "in_progess"), class: @status=="todo"? "bg-blue-100 text-white-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-yellow-900 dark:text-yellow-300" :""%>
<%= link_to  "Terminé", project_path(@project, status: "done"), class: @status=="todo"? "bg-blue-100 text-white-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-yellow-900 dark:text-yellow-300" :""%>
</div>




<%= @dontanimate %>
<% if @focused_task %>
  <div id="popupfocus" class=" <% @dontanimate ? '' : 'duration-0 translate-x-[0px]' %> duration-300 translate-x-[600px] focused_task p-3 pb-10 mb-10 absolute h-full w-[50%] bg-white z-50 right-0 top-0  transition ease-in-out  border-l-2 border-[#94F956]">
    <div class="content-description">
    <%= form_with model: [@project, @focused_task], html: { id: "edit-title-form" } do |f| %>
      <div class="font-bold text-lg mb-4 text-[50px] inline-block hover:border-[#94F956] hover:border hover:p-2  hover:rounded" id="title-task"> <%= @focused_task.name %></div>
      <div id="title-input" style="display:none">
        <%= f.text_field :name, class: "w-full p-2 border rounded border-co focus:border-[#94F956]" %>
      </div>

      <% end %>
      <%= form_with model: [@project, @focused_task], remote: true, html: { id: "edit-task-time" } do |f| %>
      <div class="text-lg flex flex-row">
        <h2 class="font-bold mr-5">Echéance :</h2>
           <% if @focused_task.time_task.present? %>
        <p id="title-time" class="hover:border-[#94F956] hover:border hover:rounded p-"><i class="fa-regular fa-calendar" style="color:#94F956"></i> <%= @focused_task.time_task.strftime("%d %b %Y à %Hh%M") %></p>
        <% else %>
        <span id="title-time-nill" class="relative inline-block p-1 border border-[#94F956] rounded text-black overflow-hidden hover:text-white hover:shadow-black before:absolute before:left-0 before:-ml-2 before:h-48 before:w-48 before:origin-top-right before:-translate-x-full before:translate-y-12 before:-rotate-90 before:bg-[#94F956] before:transition-all before:duration-300 hover:before:-rotate-180">
          <span class="relative z-10">Ajouter une échéance</span>
        </span>
      <% end %>
      </div>
      <div id="title-time-input" style="display:none;">
        <%= f.datetime_field :time_task, class: "w-full p-2 border rounded border-co focus:border-[#94F956]" %>
      </div>
      <% end %>


      <div class="flex flex-row mt-4">
        <h2 class="font-bold mr-2">Statut: </h2>
      <div>
        <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown" class="text-white bg-[#94F956] hover:bg-[#94F956] focus:ring-2 focus:outline-none focus:ring-[#94F956] font-bold rounded-lg text px-2 py-2 text-center inline-flex items-center dark:bg-[#94F956] dark:hover:bg-[#94F956] dark:focus:ring-[#94F956]" type="button">
          <%= @focused_task.status %>
          <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
          </svg>
        </button>

        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
          <ul class="py-2 text-sm text-white" aria-labelledby="dropdownDefaultButton">
            <!-- Statut "A faire" -->
            <li>
              <a href="#" class="block px-4 py-2 bg-red-900" id="statut-todo">
                A faire
              </a>
            </li>
            <!-- Statut "En progression" -->
            <li>
              <a href="#" class="block px-4 py-2 bg-yellow-500" id="statut-progress">
                En progression
              </a>
            </li>
            <!-- Statut "Terminé" -->
            <li>
              <a href="#" class="block px-4 py-2 bg-green-500" id="statut-finish">
                Terminé
              </a>
            </li>
          </ul>
        </div>
      </div>
      </div>



      <div class="focused_task_description">
        <h2 class="mb-1">Description</h2>
        <div class="description-task border rounded p-2 ml-2 mr-2 text-slate-500 mb-5" id="description">
          <%= form_with model: [@project, @focused_task], remote: true, html: { id: "edit-description-form" } do |f| %>
            <div id="description-text">
              <p><%= @focused_task.description %></p>
              <a href="#" id="edit-description" class="text-black hover:bg-[#94F956]">Modifier la description</a>
            </div>
            <div id="description-input" style="display:none;">
              <%= f.text_area :description, class: "w-full p-2 border rounded border-co focus:border-[#94F956]" %>
              <%= f.submit "Sauvegarder", class: "mt-2 text-white bg-[#94F956] hover:bg-[#94F956] font-medium rounded-lg px-4 py-2" %>
            </div>
          <% end %>
        </div>
        <div>c'est ici qu'il y aura le compteur de</div>
      </div>

      <button id="closepopup" type="button" class="text-white bg-[#94f956] hover:bg-[#94f956] focus:ring-4 focus:[#94f956] font-medium rounded-lg text-sm px-5 py-2 me-2 mb-2">
        <i class="fa-solid fa-rectangle-xmark"></i>
      </button>
    </div>
  </div>
<% end %>






<div class="task-index pt-8 w-99do">
  <div class="relative overflow-x-auto">
      <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                  <th scope="col" class="px-6 py-3">
                      Tâches
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Description
                  </th>
                  <th scope="col" class="px-6 py-3 text-center">
                      Statut
                  </th>
                  <th scope="col" class="px-6 py-3">
                      Echéance
                  </th>
              </tr>
          </thead>
         <tbody>
  <% @tasks.each do |task| %>
    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 transition-all hover:bg-gray-200 hover:border ligne">
      <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
        <%= link_to project_path(@project, focused_task: task.id), class: "no-underline text-gray-900 dark:text-white" do %>
          <p><%= task.name %></p>
        <% end %>
      </th>
      <td class="px-6 py-4">
        <%= link_to project_path(@project, focused_task: task.id), class: "no-underline text-gray-900 dark:text-white" do %>
          <p><%= task.description %></p>
        <% end %>
      </td>
      <td class="px-6 py-4 flex justify-center">
        <%= link_to project_path(@project, focused_task: task.id), class: "no-underline text-gray-900 dark:text-white" do %>
          <% case task.status %>
            <% when 'todo' %>
              <p class="bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-red-900 dark:text-red-300">A faire</p>
            <% when 'in_progess' %>
              <p class="bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-yellow-900 dark:text-yellow-300">En progression</p>
            <% else %>
              <p class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-300">Terminé</p>
          <% end %>
        <% end %>
      </td>
      <td class="px-6 py-4">
        <%= link_to project_path(@project, focused_task: task.id), class: "no-underline text-gray-900 dark:text-white" do %>
          <p><%= task.time_task.strftime("%d %b %Y à %Hh%M") if task.time_task.present? %></p>
        <% end %>
      </td>
    </tr>
  <% end %>
  <script src="https://unpkg.com/flowbite@1.5.0/dist/flowbite.js"></script>

</tbody>

      </table>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Modifier la tâche</h1>

<%= form_with model: [@project, @task], local: true do |form| %>
  <div>
    <%= form.label :name, "Nom de la tâche" %>
    <%= form.text_field :name, class: "border p-2" %>
  </div>

  <div>
    <%= form.label :description, "Description" %>
    <%= form.text_area :description, class: "border p-2" %>
  </div>

  <div>
    <%= form.label :status, "Statut" %>
    <%= form.select :status, ['todo', 'in_progress', 'done'], class: "border p-2" %>
  </div>

  <!-- Nouveau champ pour modifier la date d'échéance -->
  <div>
    <%= form.label :time_task, "Échéance de la tâche" %>
    <%= form.datetime_select :time_task, class: "border p-2" %>
  </div>

  <div class="mt-4">
    <%= form.submit "Enregistrer les modifications", class: "bg-blue-500 text-white px-4 py-2 rounded" %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Créer une nouvelle tâche pour <%= @project.name %></h1>

<%= simple_form_for([@project, @task]) do |f| %>
  <div>
    <%= f.input :name, label: "Nom de la tâche" %>
  </div>

  <div>
    <%= f.input :description, label: "Description" %>
  </div>

  <div>
    <%= f.input :status, collection: Task.statuses.keys.map { |k| [k.humanize, k] }, label: "Statut" %>
  </div>

  <div>
    <%= f.input :time_task, label: "Echéance de la tâche ", as: :datetime %>
  </div>


  <div>
    <%= f.submit "Créer la tâche", class: "btn btn-primary" %>
  </div>
<% end %>